# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeb6a30174e3a58ffccdec9f55c0e821963ab5647fb2cb1c7a21435e2db0596464c45e57b5cc950027d60e4b679cd2e2bbd9a9dd810047679858000da1588df6

test:
  secret_key_base: dafbe28e1b4eb6f5055ad3d41116d3c40109d0eb997e4a01b272856193ea655a2daf48f9e1c9b15e4c963d8e67e541fb5c53898091d6deedae1f1dd645403dc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
